// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Byte is a FIFO queue data structure.
type Byte []byte

// NewByte creates an empty byte queue.
func NewByte() *Byte {
	return &Byte{}
}

// Enqueue adds a value to queue.
func (q *Byte) Enqueue(value byte) {
	(*q) = append([]byte{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Byte) Dequeue() (byte, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Byte) Peek() (byte, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Byte) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Byte) IsEmpty() bool {
	return len(*q) == 0
}
