// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Complex64 is a FIFO queue data structure.
type Complex64 []complex64

// NewComplex64 creates an empty complex64 queue.
func NewComplex64() *Complex64 {
	return &Complex64{}
}

// Enqueue adds a value to queue.
func (q *Complex64) Enqueue(value complex64) {
	(*q) = append([]complex64{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Complex64) Dequeue() (complex64, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Complex64) Peek() (complex64, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Complex64) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Complex64) IsEmpty() bool {
	return len(*q) == 0
}
