// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Complex128 is a FIFO queue data structure.
type Complex128 []complex128

// NewComplex128 creates an empty complex128 queue.
func NewComplex128() *Complex128 {
	return &Complex128{}
}

// Enqueue adds a value to queue.
func (q *Complex128) Enqueue(value complex128) {
	(*q) = append([]complex128{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Complex128) Dequeue() (complex128, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Complex128) Peek() (complex128, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Complex128) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Complex128) IsEmpty() bool {
	return len(*q) == 0
}
