// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int is a FIFO queue data structure.
type Int []int

// NewInt creates an empty int queue.
func NewInt() *Int {
	return &Int{}
}

// Enqueue adds a value to queue.
func (q *Int) Enqueue(value int) {
	(*q) = append([]int{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int) Dequeue() (int, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int) Peek() (int, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int) IsEmpty() bool {
	return len(*q) == 0
}
