// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int16Queue is a FIFO queue data structure.
type Int16Queue []int16

// NewInt16 creates an empty int16 queue.
func NewInt16() *Int16Queue {
	return &Int16Queue{}
}

// Enqueue adds a value to queue.
func (q *Int16Queue) Enqueue(value int16) {
	(*q) = append([]int16{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int16Queue) Dequeue() (int16, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int16Queue) Peek() (int16, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int16Queue) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int16Queue) IsEmpty() bool {
	return len(*q) == 0
}
