// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int16 is a FIFO queue data structure.
type Int16 []int16

// NewInt16 creates an empty int16 queue.
func NewInt16() *Int16 {
	return &Int16{}
}

// Enqueue adds a value to queue.
func (q *Int16) Enqueue(value int16) {
	(*q) = append([]int16{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int16) Dequeue() (int16, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int16) Peek() (int16, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int16) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int16) IsEmpty() bool {
	return len(*q) == 0
}
