// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int32 is a FIFO queue data structure.
type Int32 []int32

// NewInt32 creates an empty int32 queue.
func NewInt32() *Int32 {
	return &Int32{}
}

// Enqueue adds a value to queue.
func (q *Int32) Enqueue(value int32) {
	(*q) = append([]int32{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int32) Dequeue() (int32, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int32) Peek() (int32, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int32) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int32) IsEmpty() bool {
	return len(*q) == 0
}
