// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int64 is a FIFO queue data structure.
type Int64 []int64

// NewInt64 creates an empty int64 queue.
func NewInt64() *Int64 {
	return &Int64{}
}

// Enqueue adds a value to queue.
func (q *Int64) Enqueue(value int64) {
	(*q) = append([]int64{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int64) Dequeue() (int64, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int64) Peek() (int64, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int64) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int64) IsEmpty() bool {
	return len(*q) == 0
}
