// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Int8Queue is a FIFO queue data structure.
type Int8Queue []int8

// NewInt8 creates an empty int8 queue.
func NewInt8() *Int8Queue {
	return &Int8Queue{}
}

// Enqueue adds a value to queue.
func (q *Int8Queue) Enqueue(value int8) {
	(*q) = append([]int8{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int8Queue) Dequeue() (int8, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Int8Queue) Peek() (int8, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Int8Queue) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Int8Queue) IsEmpty() bool {
	return len(*q) == 0
}
