// Code generated by "gends"; DO NOT EDIT.

package queue // import "kkn.fi/queue"

// Rune is a FIFO queue data structure.
type Rune []rune

// NewRune creates an empty rune queue.
func NewRune() *Rune {
	return &Rune{}
}

// Enqueue adds a value to queue.
func (q *Rune) Enqueue(value rune) {
	(*q) = append([]rune{value}, (*q)...)
}

// Dequeue removes the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Rune) Dequeue() (rune, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	length := len(*q) - 1
	value := (*q)[length]
	(*q) = (*q)[:length]
	return value, nil
}

// Peek returns the least recently added value.
// If called on an empty queue, will return zero value and ErrEmptyQueue.
func (q *Rune) Peek() (rune, error) {
	if len(*q) == 0 {
		return 0, ErrEmptyQueue
	}
	return (*q)[len(*q)-1], nil
}

// Len returns number of values in the queue.
func (q *Rune) Len() int {
	return len(*q)
}

// IsEmpty returns true if the queue is empty.
func (q *Rune) IsEmpty() bool {
	return len(*q) == 0
}
